### PR TITLE
SID: fixed filter off and filter resonance settings

### LINKED ISSUE #979: SID filter stuck on after toggle true to false
Setting filter to true for any oscillator causes it to be stuck on and only sets back to off after reload.

### LINKED ISSUE #980: SID filter resonance bits stuck on
The filter resonance bits will only be toggled on and changing the filter resonance value will not be heard until after a reload.

If the value is F lowering the value of filter resonance will not be set in the SID chip. like wise moving from 3 to 4 would actually yield a value of 7 in the SID chip filter resonance register.

### PR DESCRIPTION
**Pull request by chrcav**
fixes #979 and fixes #980:

clear osc filter enable bit and filter response bits before setting resonance and filter on bits.

### CODE REVIEW

**Comment by maks** [comment]
@chrcav thanks so much for submitting this PR and your other one! 🙏🏻 👍🏻 
We're a bit pressed right now with work on the upcoming release and Advance launch but we'll try to review the PR as soon as we can.

**Comment by chrcav** [comment]
@maks I totally understand and see all the effort going into the release. Excited for the Advance launch. 🚀

File: sources/Application/Instruments/SIDInstrument.cpp [hunk 1]
```diff
@@ -164,7 +164,8 @@ bool SIDInstrument::Start(int c, unsigned char note, bool retrigger) {
   sid_->Register[22] = fltcut_->GetInt() >> 3;  // Filter Cut Hi
 
   // on start for each instrument it sets it's own filter in this register
-  sid_->Register[23] = sid_->Register[23] | fltres_->GetInt() << 4 |
+  sid_->Register[23] = (sid_->Register[23] & 0xF & ~(1 << osc)) |
```
Comment (democloid) [inline sources/Application/Instruments/SIDInstrument.cpp:170]: This is correct, thou `& 0xF` is not really needed

Comment (chrcav) [reply sources/Application/Instruments/SIDInstrument.cpp:170]: I added `& 0xF` to fix the filter resonance value setting. Without that I was seeing that the filter resonance would get stuck at the highest value.

Comment (chrcav) [reply sources/Application/Instruments/SIDInstrument.cpp:170]: I did just verify that removing `& 0xF` from that line causes the filter resonance value to not update correctly.

Comment (democloid) [reply sources/Application/Instruments/SIDInstrument.cpp:170]: yeah that makes sense, but then if it's the case that we need to clear the whole register and then set the right bits maybe it makes more sense and it's more clear to just leave the original code but just clear the register beforehand, no?

I suspect there might be other such issues in other places, so maybe it would be good to check all registers initialization

Comment (chrcav) [reply sources/Application/Instruments/SIDInstrument.cpp:170]: This is the only Register that has both a shared value for all oscillators (filter resonance) and oscillator specific bits (filter on/off). I agree that it feels a bit silly to clear 5 bits of this register. We're effectively masking off the 2 other filter on bits since the current `SIDInstrument` doesn't know what value the other `vfon_` fields are set to. I should really distill some of this info into a comment since it is unclear why we aren't resetting the whole register.

Checking over the rest of the Registers this is the only one we preserve the existing value. All the other Registers get thrown out and set back to exactly what is in the instrument fields. Doing the same for this Register would result in the filter being turned off for all but one oscillator at a time.

**Review by democloid — APPROVED** [review]
Thanks!
